// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: AqyDisp

#ifndef _AQYDISP_UI_H
#define _AQYDISP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ServiceScreen.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * CustomFadeIn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * CustomFadeOut_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_KazakhFontNovo36);
LV_FONT_DECLARE(ui_font_KazakhFontNovoNumbers140);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
