// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "OTA/ota.h"
#include "Sensors/sensors.h"

extern void simple_ota_example_task();

void checkOrderUpdates(lv_event_t * e)
{
	// Your code here
};
