// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void populateWiFiList(lv_event_t * e);
void ota_custom_update(lv_event_t * e);
void startCO2Task(lv_event_t * e);
void startH2Task(lv_event_t * e);
void startTemperatureTask(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
