// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "OTA/ota.h"

extern void simple_ota_example_task();

void ota_custom_update(lv_event_t * e)
{
	
	
	if (xTaskCreate(&simple_ota_example_task,
                    "ota_example_task",
                    8192, NULL, 5, NULL) != pdPASS)
    {
        ESP_LOGE(TAG, "OTA task not created");
    }
	else {
		ESP_LOGE(TAG, "Nice!!!!");
	}

}
