// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Chart1;
lv_obj_t * ui_graphScreen = NULL;
lv_obj_t * ui_chartContainer = NULL;
lv_obj_t * ui_theChart = NULL;
lv_obj_t * ui_theChart_Xaxis = NULL;
lv_obj_t * ui_theChart_Yaxis1 = NULL;
lv_obj_t * ui_theChart_Yaxis2 = NULL;
lv_obj_t * ui_graphSettingsImageButton = NULL;
lv_obj_t * ui_zoomInButton = NULL;
lv_obj_t * ui_zoomInLabel = NULL;
lv_obj_t * ui_zoomOutButton = NULL;
lv_obj_t * ui_zoomOutLabel = NULL;
// event funtions
void ui_event_graphScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        startCO2Graph(e);
    }
}

// build funtions

void ui_graphScreen_screen_init(void)
{
    ui_graphScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_graphScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chartContainer = lv_obj_create(ui_graphScreen);
    lv_obj_remove_style_all(ui_chartContainer);
    lv_obj_set_width(ui_chartContainer, 398);
    lv_obj_set_height(ui_chartContainer, 286);
    lv_obj_set_x(ui_chartContainer, -23);
    lv_obj_set_y(ui_chartContainer, -2);
    lv_obj_set_align(ui_chartContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_chartContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_theChart = lv_chart_create(ui_chartContainer);
    lv_obj_set_width(ui_theChart, 361);
    lv_obj_set_height(ui_theChart, 252);
    lv_obj_set_x(ui_theChart, 22);
    lv_obj_set_y(ui_theChart, -7);
    lv_obj_set_align(ui_theChart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_theChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_add_flag(ui_theChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_theChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_theChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_theChart, 100);
    lv_chart_set_range(ui_theChart, LV_CHART_AXIS_PRIMARY_Y, 0, 1000);
    lv_chart_set_range(ui_theChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);

    ui_theChart_Xaxis = lv_scale_create(ui_theChart);
    lv_scale_set_mode(ui_theChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_theChart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_theChart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_theChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_theChart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_theChart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_theChart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_theChart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_theChart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_theChart_Xaxis, 12, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_theChart_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_theChart_Xaxis, 0, 10 > 0 ? 10 - 1 : 0);
    lv_scale_set_total_tick_count(ui_theChart_Xaxis, (10 > 0 ? 10 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_theChart_Xaxis, 2 >= 1 ? 2 : 1);
    ui_theChart_Yaxis1 = lv_scale_create(ui_theChart);
    lv_scale_set_mode(ui_theChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_theChart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_theChart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_theChart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_theChart,
                                                                     LV_PART_MAIN) - lv_obj_get_style_border_width(ui_theChart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_theChart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_theChart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_theChart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_theChart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_theChart_Yaxis1, 8, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_theChart_Yaxis1,  0, 1000);
    lv_scale_set_total_tick_count(ui_theChart_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_theChart_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_obj_add_flag(ui_theChart_Yaxis1, LV_OBJ_FLAG_FLOATING);
    lv_obj_clear_flag(ui_theChart_Yaxis1, LV_OBJ_FLAG_SCROLLABLE);

    ui_theChart_Yaxis2 = lv_scale_create(ui_theChart);
    lv_scale_set_mode(ui_theChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_theChart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_theChart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_theChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_theChart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_theChart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_theChart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_theChart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_theChart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_theChart_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_theChart_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_theChart_Yaxis2,  0, 0);
    lv_scale_set_total_tick_count(ui_theChart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_theChart_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_theChart_Yaxis2, false);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_theChart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_theChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_graphSettingsImageButton = lv_imagebutton_create(ui_graphScreen);
    lv_imagebutton_set_src(ui_graphSettingsImageButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_settings_png, NULL);
    lv_obj_set_width(ui_graphSettingsImageButton, 30);
    lv_obj_set_height(ui_graphSettingsImageButton, 30);
    lv_obj_set_x(ui_graphSettingsImageButton, 209);
    lv_obj_set_y(ui_graphSettingsImageButton, 72);
    lv_obj_set_align(ui_graphSettingsImageButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_graphSettingsImageButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_graphSettingsImageButton, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_graphSettingsImageButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_graphSettingsImageButton, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_graphSettingsImageButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_graphSettingsImageButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_graphSettingsImageButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zoomInButton = lv_button_create(ui_graphScreen);
    lv_obj_set_width(ui_zoomInButton, 30);
    lv_obj_set_height(ui_zoomInButton, 30);
    lv_obj_set_x(ui_zoomInButton, 203);
    lv_obj_set_y(ui_zoomInButton, -73);
    lv_obj_set_align(ui_zoomInButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zoomInButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_zoomInButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zoomInButton, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zoomInButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zoomInLabel = lv_label_create(ui_zoomInButton);
    lv_obj_set_width(ui_zoomInLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zoomInLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_zoomInLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zoomInLabel, "+");

    ui_zoomOutButton = lv_button_create(ui_graphScreen);
    lv_obj_set_width(ui_zoomOutButton, 30);
    lv_obj_set_height(ui_zoomOutButton, 30);
    lv_obj_set_x(ui_zoomOutButton, 203);
    lv_obj_set_y(ui_zoomOutButton, -35);
    lv_obj_set_align(ui_zoomOutButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zoomOutButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_zoomOutButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zoomOutButton, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zoomOutButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zoomOutLabel = lv_label_create(ui_zoomOutButton);
    lv_obj_set_width(ui_zoomOutLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zoomOutLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zoomOutLabel, -1);
    lv_obj_set_y(ui_zoomOutLabel, 8);
    lv_obj_set_align(ui_zoomOutLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zoomOutLabel, "-\n");


    //lv_chart_cursor_t * ui_cursor1 = lv_chart_add_cursor(uic_Chart1, lv_color_hex(0x6C42C1), LV_DIR_BOTTOM);

    lv_obj_add_event_cb(ui_graphScreen, ui_event_graphScreen, LV_EVENT_ALL, NULL);
    uic_Chart1 = ui_theChart;

}

void ui_graphScreen_screen_destroy(void)
{
    if(ui_graphScreen) lv_obj_del(ui_graphScreen);

    // NULL screen variables
    ui_graphScreen = NULL;
    ui_chartContainer = NULL;
    uic_Chart1 = NULL;
    ui_theChart = NULL;
    ui_graphSettingsImageButton = NULL;
    ui_zoomInButton = NULL;
    ui_zoomInLabel = NULL;
    ui_zoomOutButton = NULL;
    ui_zoomOutLabel = NULL;

}
