// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_GRAPHSCREEN_H
#define UI_GRAPHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_graphScreen
extern void ui_graphScreen_screen_init(void);
extern void ui_graphScreen_screen_destroy(void);
extern lv_obj_t * ui_graphScreen;
extern lv_obj_t * ui_chartContainer;
extern lv_obj_t * ui_theChart;
extern lv_obj_t * ui_theChart_Xaxis;
extern lv_obj_t * ui_theChart_Yaxis1;
extern lv_obj_t * ui_theChart_Yaxis2;
extern lv_obj_t * ui_graphSettingsImageButton;
extern lv_obj_t * ui_zoomInButton;
extern lv_obj_t * ui_zoomInLabel;
extern lv_obj_t * ui_zoomOutButton;
extern lv_obj_t * ui_zoomOutLabel;
extern lv_chart_series_t * mq8_series;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Chart1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

