// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_homeScreen = NULL;
lv_obj_t * ui_ChartButton = NULL;
lv_obj_t * ui_TODOButton1 = NULL;
lv_obj_t * ui_TODOButton2 = NULL;
lv_obj_t * ui_TODOButton3 = NULL;
lv_obj_t * ui_TODOButton4 = NULL;
lv_obj_t * ui_TODOButton5 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_topMenuContainer = NULL;
lv_obj_t * ui_wifiImageButton = NULL;
lv_obj_t * ui_settingsImage = NULL;
lv_obj_t * ui_wifiConnectionStatusLabel = NULL;
lv_obj_t * ui_wifiWarningImage = NULL;
lv_obj_t * ui_wifiKeyboard = NULL;
lv_obj_t * ui_wifiMenu = NULL;
lv_obj_t * ui_wifiInfoLabel = NULL;
lv_obj_t * ui_wifiSwitch = NULL;
lv_obj_t * ui_wifiListPanel = NULL;
lv_obj_t * ui_wifiInfoImage = NULL;
lv_obj_t * ui_wifiMenuCancelButton = NULL;
lv_obj_t * ui_wifiScanningImage = NULL;
lv_obj_t * ui_wifiScanningLabel = NULL;
lv_obj_t * ui_wifiEnterPanel = NULL;
lv_obj_t * ui_selectedWiFiLabel = NULL;
lv_obj_t * ui_wifiPasswordTextInput = NULL;
lv_obj_t * ui_connectWifiButton = NULL;
lv_obj_t * ui_connectWiFiText = NULL;
lv_obj_t * ui_TUploadCancelWifiButton = NULL;
lv_obj_t * ui_TUploadCancelWifiConnectionButton = NULL;
// event funtions
void ui_event_ChartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_instructionsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_instructionsScreen_screen_init);
    }
}

void ui_event_wifiImageButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CustomFadeIn_Animation(ui_wifiMenu, 0);
        _ui_flag_modify(ui_ChartButton, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_wifiMenu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_settingsImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settingsScreen_screen_init);
    }
}

void ui_event_wifiKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_wifiKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_wifiSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        populateWiFiList(e);
    }
}

void ui_event_wifiMenuCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CustomFadeOut_Animation(ui_wifiMenu, 0);
        _ui_flag_modify(ui_ChartButton, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifiMenu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TUploadCancelWifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ota_custom_update(e);
    }
}

// build funtions

void ui_homeScreen_screen_init(void)
{
    ui_homeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartButton = lv_button_create(ui_homeScreen);
    lv_obj_set_width(ui_ChartButton, 128);
    lv_obj_set_height(ui_ChartButton, 221);
    lv_obj_set_x(ui_ChartButton, -149);
    lv_obj_set_y(ui_ChartButton, 16);
    lv_obj_set_align(ui_ChartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ChartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChartButton, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TODOButton1 = lv_button_create(ui_homeScreen);
    lv_obj_set_width(ui_TODOButton1, 128);
    lv_obj_set_height(ui_TODOButton1, 83);
    lv_obj_set_x(ui_TODOButton1, 7);
    lv_obj_set_y(ui_TODOButton1, -44);
    lv_obj_set_align(ui_TODOButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TODOButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TODOButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TODOButton1, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TODOButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TODOButton2 = lv_button_create(ui_homeScreen);
    lv_obj_set_width(ui_TODOButton2, 137);
    lv_obj_set_height(ui_TODOButton2, 104);
    lv_obj_set_x(ui_TODOButton2, 12);
    lv_obj_set_y(ui_TODOButton2, 72);
    lv_obj_set_align(ui_TODOButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TODOButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TODOButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TODOButton2, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TODOButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TODOButton3 = lv_button_create(ui_homeScreen);
    lv_obj_set_width(ui_TODOButton3, 80);
    lv_obj_set_height(ui_TODOButton3, 79);
    lv_obj_set_x(ui_TODOButton3, 146);
    lv_obj_set_y(ui_TODOButton3, 73);
    lv_obj_set_align(ui_TODOButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TODOButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TODOButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TODOButton3, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TODOButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TODOButton4 = lv_button_create(ui_homeScreen);
    lv_obj_set_width(ui_TODOButton4, 86);
    lv_obj_set_height(ui_TODOButton4, 79);
    lv_obj_set_x(ui_TODOButton4, 143);
    lv_obj_set_y(ui_TODOButton4, -30);
    lv_obj_set_align(ui_TODOButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TODOButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TODOButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TODOButton4, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TODOButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TODOButton5 = lv_button_create(ui_homeScreen);
    lv_obj_set_width(ui_TODOButton5, 80);
    lv_obj_set_height(ui_TODOButton5, 79);
    lv_obj_set_x(ui_TODOButton5, 146);
    lv_obj_set_y(ui_TODOButton5, 73);
    lv_obj_set_align(ui_TODOButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TODOButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TODOButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TODOButton5, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TODOButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_homeScreen);
    lv_image_set_src(ui_Image4, &ui_img_chart_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image4, -149);
    lv_obj_set_y(ui_Image4, 12);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Image4, LV_STATE_DISABLED);       /// States
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_topMenuContainer = lv_obj_create(ui_homeScreen);
    lv_obj_remove_style_all(ui_topMenuContainer);
    lv_obj_set_width(ui_topMenuContainer, 483);
    lv_obj_set_height(ui_topMenuContainer, 42);
    lv_obj_set_x(ui_topMenuContainer, -2);
    lv_obj_set_y(ui_topMenuContainer, -139);
    lv_obj_set_align(ui_topMenuContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topMenuContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_topMenuContainer, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topMenuContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiImageButton = lv_imagebutton_create(ui_topMenuContainer);
    lv_imagebutton_set_src(ui_wifiImageButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_473763830, NULL);
    lv_obj_set_width(ui_wifiImageButton, 30);
    lv_obj_set_height(ui_wifiImageButton, 30);
    lv_obj_set_x(ui_wifiImageButton, 151);
    lv_obj_set_y(ui_wifiImageButton, -2);
    lv_obj_set_align(ui_wifiImageButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_wifiImageButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiImageButton, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiImageButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_wifiImageButton, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_wifiImageButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_wifiImageButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_wifiImageButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsImage = lv_imagebutton_create(ui_topMenuContainer);
    lv_imagebutton_set_src(ui_settingsImage, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_settings_png, NULL);
    lv_obj_set_width(ui_settingsImage, 30);
    lv_obj_set_height(ui_settingsImage, 30);
    lv_obj_set_x(ui_settingsImage, 206);
    lv_obj_set_y(ui_settingsImage, -1);
    lv_obj_set_align(ui_settingsImage, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_settingsImage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingsImage, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_settingsImage, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_settingsImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_settingsImage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_settingsImage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnectionStatusLabel = lv_label_create(ui_topMenuContainer);
    lv_obj_set_width(ui_wifiConnectionStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiConnectionStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiConnectionStatusLabel, 29);
    lv_obj_set_y(ui_wifiConnectionStatusLabel, -2);
    lv_obj_set_align(ui_wifiConnectionStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiConnectionStatusLabel, "Not connected to WiFi!");
    lv_obj_set_style_text_color(ui_wifiConnectionStatusLabel, lv_color_hex(0xDAC7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiConnectionStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiWarningImage = lv_image_create(ui_topMenuContainer);
    lv_image_set_src(ui_wifiWarningImage, &ui_img_996158111);
    lv_obj_set_width(ui_wifiWarningImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiWarningImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiWarningImage, -79);
    lv_obj_set_y(ui_wifiWarningImage, -2);
    lv_obj_set_align(ui_wifiWarningImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiWarningImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiWarningImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiKeyboard = lv_keyboard_create(ui_homeScreen);
    lv_obj_set_width(ui_wifiKeyboard, 478);
    lv_obj_set_height(ui_wifiKeyboard, 150);
    lv_obj_set_x(ui_wifiKeyboard, 1);
    lv_obj_set_y(ui_wifiKeyboard, 86);
    lv_obj_set_align(ui_wifiKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_wifiMenu = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_wifiMenu, 384);
    lv_obj_set_height(ui_wifiMenu, 259);
    lv_obj_set_x(ui_wifiMenu, 11);
    lv_obj_set_y(ui_wifiMenu, -4);
    lv_obj_set_align(ui_wifiMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiMenu, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_wifiMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiInfoLabel = lv_label_create(ui_wifiMenu);
    lv_obj_set_width(ui_wifiInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiInfoLabel, -113);
    lv_obj_set_y(ui_wifiInfoLabel, -106);
    lv_obj_set_align(ui_wifiInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiInfoLabel, "WiFi");

    ui_wifiSwitch = lv_switch_create(ui_wifiMenu);
    lv_obj_set_width(ui_wifiSwitch, 48);
    lv_obj_set_height(ui_wifiSwitch, 25);
    lv_obj_set_x(ui_wifiSwitch, -58);
    lv_obj_set_y(ui_wifiSwitch, -106);
    lv_obj_set_align(ui_wifiSwitch, LV_ALIGN_CENTER);

    ui_wifiListPanel = lv_obj_create(ui_wifiMenu);
    lv_obj_set_width(ui_wifiListPanel, 339);
    lv_obj_set_height(ui_wifiListPanel, 200);
    lv_obj_set_x(ui_wifiListPanel, -2);
    lv_obj_set_y(ui_wifiListPanel, 14);
    lv_obj_set_align(ui_wifiListPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiListPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiInfoImage = lv_image_create(ui_wifiMenu);
    lv_image_set_src(ui_wifiInfoImage, &ui_img_338993590);
    lv_obj_set_width(ui_wifiInfoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiInfoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiInfoImage, -154);
    lv_obj_set_y(ui_wifiInfoImage, -107);
    lv_obj_set_align(ui_wifiInfoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiInfoImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiInfoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiMenuCancelButton = lv_imagebutton_create(ui_wifiMenu);
    lv_imagebutton_set_src(ui_wifiMenuCancelButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_round_back_png, NULL);
    lv_obj_set_width(ui_wifiMenuCancelButton, 30);
    lv_obj_set_height(ui_wifiMenuCancelButton, 30);
    lv_obj_set_x(ui_wifiMenuCancelButton, 147);
    lv_obj_set_y(ui_wifiMenuCancelButton, -107);
    lv_obj_set_align(ui_wifiMenuCancelButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_wifiMenuCancelButton, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiMenuCancelButton, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiMenuCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_wifiMenuCancelButton, lv_color_hex(0x6C42C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_wifiMenuCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_wifiMenuCancelButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_wifiMenuCancelButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiScanningImage = lv_image_create(ui_wifiMenu);
    lv_image_set_src(ui_wifiScanningImage, &ui_img_wait_png);
    lv_obj_set_width(ui_wifiScanningImage, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_wifiScanningImage, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_wifiScanningImage, 11);
    lv_obj_set_y(ui_wifiScanningImage, -107);
    lv_obj_set_align(ui_wifiScanningImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiScanningImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiScanningImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiScanningLabel = lv_label_create(ui_wifiMenu);
    lv_obj_set_width(ui_wifiScanningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiScanningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiScanningLabel, 70);
    lv_obj_set_y(ui_wifiScanningLabel, -106);
    lv_obj_set_align(ui_wifiScanningLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiScanningLabel, "Scanning...");
    lv_obj_add_flag(ui_wifiScanningLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_wifiEnterPanel = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_wifiEnterPanel, 326);
    lv_obj_set_height(ui_wifiEnterPanel, 154);
    lv_obj_set_x(ui_wifiEnterPanel, 5);
    lv_obj_set_y(ui_wifiEnterPanel, -66);
    lv_obj_set_align(ui_wifiEnterPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiEnterPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_wifiEnterPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_selectedWiFiLabel = lv_label_create(ui_wifiEnterPanel);
    lv_obj_set_width(ui_selectedWiFiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_selectedWiFiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectedWiFiLabel, -73);
    lv_obj_set_y(ui_selectedWiFiLabel, -53);
    lv_obj_set_align(ui_selectedWiFiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_selectedWiFiLabel, "Selected WiFi SSID: ");

    ui_wifiPasswordTextInput = lv_textarea_create(ui_wifiEnterPanel);
    lv_obj_set_width(ui_wifiPasswordTextInput, 260);
    lv_obj_set_height(ui_wifiPasswordTextInput, 56);
    lv_obj_set_x(ui_wifiPasswordTextInput, -17);
    lv_obj_set_y(ui_wifiPasswordTextInput, -9);
    lv_obj_set_align(ui_wifiPasswordTextInput, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifiPasswordTextInput, "Enter the password...");

    ui_connectWifiButton = lv_button_create(ui_wifiEnterPanel);
    lv_obj_set_width(ui_connectWifiButton, 88);
    lv_obj_set_height(ui_connectWifiButton, 38);
    lv_obj_set_x(ui_connectWifiButton, 46);
    lv_obj_set_y(ui_connectWifiButton, 47);
    lv_obj_set_align(ui_connectWifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_connectWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_connectWifiButton, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectWiFiText = lv_label_create(ui_connectWifiButton);
    lv_obj_set_width(ui_connectWiFiText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connectWiFiText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connectWiFiText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connectWiFiText, "Connect");

    ui_TUploadCancelWifiButton = lv_button_create(ui_wifiEnterPanel);
    lv_obj_set_width(ui_TUploadCancelWifiButton, 88);
    lv_obj_set_height(ui_TUploadCancelWifiButton, 38);
    lv_obj_set_x(ui_TUploadCancelWifiButton, -62);
    lv_obj_set_y(ui_TUploadCancelWifiButton, 47);
    lv_obj_set_align(ui_TUploadCancelWifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TUploadCancelWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TUploadCancelWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TUploadCancelWifiButton, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TUploadCancelWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TUploadCancelWifiConnectionButton = lv_label_create(ui_TUploadCancelWifiButton);
    lv_obj_set_width(ui_TUploadCancelWifiConnectionButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TUploadCancelWifiConnectionButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TUploadCancelWifiConnectionButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TUploadCancelWifiConnectionButton, "TUpload");

    lv_obj_add_event_cb(ui_ChartButton, ui_event_ChartButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiImageButton, ui_event_wifiImageButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsImage, ui_event_settingsImage, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_wifiKeyboard, ui_wifiPasswordTextInput);
    lv_obj_add_event_cb(ui_wifiKeyboard, ui_event_wifiKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiSwitch, ui_event_wifiSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiMenuCancelButton, ui_event_wifiMenuCancelButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TUploadCancelWifiButton, ui_event_TUploadCancelWifiButton, LV_EVENT_ALL, NULL);

}

void ui_homeScreen_screen_destroy(void)
{
    if(ui_homeScreen) lv_obj_del(ui_homeScreen);

    // NULL screen variables
    ui_homeScreen = NULL;
    ui_ChartButton = NULL;
    ui_TODOButton1 = NULL;
    ui_TODOButton2 = NULL;
    ui_TODOButton3 = NULL;
    ui_TODOButton4 = NULL;
    ui_TODOButton5 = NULL;
    ui_Image4 = NULL;
    ui_topMenuContainer = NULL;
    ui_wifiImageButton = NULL;
    ui_settingsImage = NULL;
    ui_wifiConnectionStatusLabel = NULL;
    ui_wifiWarningImage = NULL;
    ui_wifiKeyboard = NULL;
    ui_wifiMenu = NULL;
    ui_wifiInfoLabel = NULL;
    ui_wifiSwitch = NULL;
    ui_wifiListPanel = NULL;
    ui_wifiInfoImage = NULL;
    ui_wifiMenuCancelButton = NULL;
    ui_wifiScanningImage = NULL;
    ui_wifiScanningLabel = NULL;
    ui_wifiEnterPanel = NULL;
    ui_selectedWiFiLabel = NULL;
    ui_wifiPasswordTextInput = NULL;
    ui_connectWifiButton = NULL;
    ui_connectWiFiText = NULL;
    ui_TUploadCancelWifiButton = NULL;
    ui_TUploadCancelWifiConnectionButton = NULL;

}
