// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_homeScreen
extern void ui_homeScreen_screen_init(void);
extern void ui_homeScreen_screen_destroy(void);
extern lv_obj_t * ui_homeScreen;
extern void ui_event_ChartButton(lv_event_t * e);
extern lv_obj_t * ui_ChartButton;
extern lv_obj_t * ui_TODOButton1;
extern lv_obj_t * ui_TODOButton2;
extern lv_obj_t * ui_TODOButton3;
extern lv_obj_t * ui_TODOButton4;
extern lv_obj_t * ui_TODOButton5;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_topMenuContainer;
extern void ui_event_wifiImageButton(lv_event_t * e);
extern lv_obj_t * ui_wifiImageButton;
extern void ui_event_settingsImage(lv_event_t * e);
extern lv_obj_t * ui_settingsImage;
extern lv_obj_t * ui_wifiConnectionStatusLabel;
extern lv_obj_t * ui_wifiWarningImage;
extern void ui_event_wifiKeyboard(lv_event_t * e);
extern lv_obj_t * ui_wifiKeyboard;
extern lv_obj_t * ui_wifiMenu;
extern lv_obj_t * ui_wifiInfoLabel;
extern void ui_event_wifiSwitch(lv_event_t * e);
extern lv_obj_t * ui_wifiSwitch;
extern lv_obj_t * ui_wifiListPanel;
extern lv_obj_t * ui_wifiInfoImage;
extern void ui_event_wifiMenuCancelButton(lv_event_t * e);
extern lv_obj_t * ui_wifiMenuCancelButton;
extern lv_obj_t * ui_wifiScanningImage;
extern lv_obj_t * ui_wifiScanningLabel;
extern lv_obj_t * ui_wifiEnterPanel;
extern lv_obj_t * ui_selectedWiFiLabel;
extern lv_obj_t * ui_wifiPasswordTextInput;
extern lv_obj_t * ui_connectWifiButton;
extern lv_obj_t * ui_connectWiFiText;
extern void ui_event_TUploadCancelWifiButton(lv_event_t * e);
extern lv_obj_t * ui_TUploadCancelWifiButton;
extern lv_obj_t * ui_TUploadCancelWifiConnectionButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

