// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_instructionsScreen = NULL;
lv_obj_t * ui_TODOTEXTLABEL = NULL;
lv_obj_t * ui_InstructContinueButton = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_InstructContinueButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_graphScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_graphScreen_screen_init);
    }
}

// build funtions

void ui_instructionsScreen_screen_init(void)
{
    ui_instructionsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_instructionsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TODOTEXTLABEL = lv_label_create(ui_instructionsScreen);
    lv_obj_set_width(ui_TODOTEXTLABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TODOTEXTLABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TODOTEXTLABEL, 3);
    lv_obj_set_y(ui_TODOTEXTLABEL, -71);
    lv_obj_set_align(ui_TODOTEXTLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TODOTEXTLABEL,
                      "TODO: There would be nice visual instructions\nand 3 step detection of the sensor as well as\nsteps to configure the initial graph settings\nsuch as sampling frequency, whether or not\nto store it in the web server (which we will test wifi)\nconnection for, etc.");

    ui_InstructContinueButton = lv_button_create(ui_instructionsScreen);
    lv_obj_set_width(ui_InstructContinueButton, 124);
    lv_obj_set_height(ui_InstructContinueButton, 79);
    lv_obj_set_x(ui_InstructContinueButton, -1);
    lv_obj_set_y(ui_InstructContinueButton, 77);
    lv_obj_set_align(ui_InstructContinueButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InstructContinueButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_InstructContinueButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InstructContinueButton, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InstructContinueButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_InstructContinueButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Continue on");

    lv_obj_add_event_cb(ui_InstructContinueButton, ui_event_InstructContinueButton, LV_EVENT_ALL, NULL);

}

void ui_instructionsScreen_screen_destroy(void)
{
    if(ui_instructionsScreen) lv_obj_del(ui_instructionsScreen);

    // NULL screen variables
    ui_instructionsScreen = NULL;
    ui_TODOTEXTLABEL = NULL;
    ui_InstructContinueButton = NULL;
    ui_Label5 = NULL;

}
