// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_INSTRUCTIONSSCREEN_H
#define UI_INSTRUCTIONSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_instructionsScreen
extern void ui_instructionsScreen_screen_init(void);
extern void ui_instructionsScreen_screen_destroy(void);
extern lv_obj_t * ui_instructionsScreen;
extern lv_obj_t * ui_TODOTEXTLABEL;
extern void ui_event_InstructContinueButton(lv_event_t * e);
extern lv_obj_t * ui_InstructContinueButton;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

