// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_LOGOSCREEN_H
#define UI_LOGOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_logoScreen
extern void ui_logoScreen_screen_init(void);
extern void ui_logoScreen_screen_destroy(void);
extern void ui_event_logoScreen(lv_event_t * e);
extern lv_obj_t * ui_logoScreen;
extern lv_obj_t * ui_logoImage;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

