// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_logoScreen = NULL;
lv_obj_t * ui_logoImage = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_logoScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 3000, &ui_homeScreen_screen_init);
    }
}

// build funtions

void ui_logoScreen_screen_init(void)
{
    ui_logoScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_logoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logoImage = lv_image_create(ui_logoScreen);
    lv_image_set_src(ui_logoImage, &ui_img_logo_png);
    lv_obj_set_width(ui_logoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logoImage, 0);
    lv_obj_set_y(ui_logoImage, -16);
    lv_obj_set_align(ui_logoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logoImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_logoScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 103);
    lv_obj_set_y(ui_Label2, 71);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Science - made easy");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_logoScreen, ui_event_logoScreen, LV_EVENT_ALL, NULL);

}

void ui_logoScreen_screen_destroy(void)
{
    if(ui_logoScreen) lv_obj_del(ui_logoScreen);

    // NULL screen variables
    ui_logoScreen = NULL;
    ui_logoImage = NULL;
    ui_Label2 = NULL;

}
