// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_settingsScreen = NULL;
// event funtions

// build funtions

void ui_settingsScreen_screen_init(void)
{
    ui_settingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_settingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_settingsScreen_screen_destroy(void)
{
    if(ui_settingsScreen) lv_obj_del(ui_settingsScreen);

    // NULL screen variables
    ui_settingsScreen = NULL;

}
