// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: AqyDisp

#ifndef UI_SERVICESCREEN_H
#define UI_SERVICESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ServiceScreen
extern void ui_ServiceScreen_screen_init(void);
extern void ui_ServiceScreen_screen_destroy(void);
extern void ui_event_ServiceScreen(lv_event_t * e);
extern lv_obj_t * ui_ServiceScreen;
extern lv_obj_t * ui_readyNumberLabel;
extern lv_obj_t * ui_readyNameLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

