// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_sensorChooseScreen = NULL;
lv_obj_t * ui_chooseCO2Button = NULL;
lv_obj_t * ui_chooseCO2Label = NULL;
lv_obj_t * ui_chooseTemperatureButton = NULL;
lv_obj_t * ui_chooseTemperatureLabel = NULL;
lv_obj_t * ui_chooseH2Button = NULL;
lv_obj_t * ui_chooseH2Label = NULL;
// event funtions
void ui_event_chooseCO2Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_graphScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_graphScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        startCO2Task(e);
    }
}

void ui_event_chooseTemperatureButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_graphScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_graphScreen_screen_init);
        //startH2Task(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        startTemperatureTask(e);
    }
}

// build funtions

void ui_sensorChooseScreen_screen_init(void)
{
    ui_sensorChooseScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sensorChooseScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chooseCO2Button = lv_button_create(ui_sensorChooseScreen);
    lv_obj_set_width(ui_chooseCO2Button, 128);
    lv_obj_set_height(ui_chooseCO2Button, 83);
    lv_obj_set_x(ui_chooseCO2Button, -134);
    lv_obj_set_y(ui_chooseCO2Button, -48);
    lv_obj_set_align(ui_chooseCO2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chooseCO2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_chooseCO2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chooseCO2Button, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chooseCO2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chooseCO2Label = lv_label_create(ui_chooseCO2Button);
    lv_obj_set_width(ui_chooseCO2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chooseCO2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_chooseCO2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chooseCO2Label, "CO2");

    ui_chooseTemperatureButton = lv_button_create(ui_sensorChooseScreen);
    lv_obj_set_width(ui_chooseTemperatureButton, 128);
    lv_obj_set_height(ui_chooseTemperatureButton, 83);
    lv_obj_set_x(ui_chooseTemperatureButton, -1);
    lv_obj_set_y(ui_chooseTemperatureButton, 70);
    lv_obj_set_align(ui_chooseTemperatureButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chooseTemperatureButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_chooseTemperatureButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chooseTemperatureButton, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chooseTemperatureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chooseTemperatureLabel = lv_label_create(ui_chooseTemperatureButton);
    lv_obj_set_width(ui_chooseTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chooseTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_chooseTemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chooseTemperatureLabel, "Temperature");

    ui_chooseH2Button = lv_button_create(ui_sensorChooseScreen);
    lv_obj_set_width(ui_chooseH2Button, 128);
    lv_obj_set_height(ui_chooseH2Button, 83);
    lv_obj_set_x(ui_chooseH2Button, 140);
    lv_obj_set_y(ui_chooseH2Button, -45);
    lv_obj_set_align(ui_chooseH2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chooseH2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_chooseH2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chooseH2Button, lv_color_hex(0x8C52FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chooseH2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chooseH2Label = lv_label_create(ui_chooseH2Button);
    lv_obj_set_width(ui_chooseH2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chooseH2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_chooseH2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chooseH2Label, "Temperature");

    lv_obj_add_event_cb(ui_chooseCO2Button, ui_event_chooseCO2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chooseTemperatureButton, ui_event_chooseTemperatureButton, LV_EVENT_ALL, NULL);

}

void ui_sensorChooseScreen_screen_destroy(void)
{
    if(ui_sensorChooseScreen) lv_obj_del(ui_sensorChooseScreen);

    // NULL screen variables
    ui_sensorChooseScreen = NULL;
    ui_chooseCO2Button = NULL;
    ui_chooseCO2Label = NULL;
    ui_chooseTemperatureButton = NULL;
    ui_chooseTemperatureLabel = NULL;
    ui_chooseH2Button = NULL;
    ui_chooseH2Label = NULL;

}
