// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SENSORCHOOSESCREEN_H
#define UI_SENSORCHOOSESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sensorChooseScreen
extern void ui_sensorChooseScreen_screen_init(void);
extern void ui_sensorChooseScreen_screen_destroy(void);
extern lv_obj_t * ui_sensorChooseScreen;
extern void ui_event_chooseCO2Button(lv_event_t * e);
extern lv_obj_t * ui_chooseCO2Button;
extern lv_obj_t * ui_chooseCO2Label;
extern void ui_event_chooseTemperatureButton(lv_event_t * e);
extern lv_obj_t * ui_chooseTemperatureButton;
extern lv_obj_t * ui_chooseTemperatureLabel;
extern lv_obj_t * ui_chooseH2Button;
extern lv_obj_t * ui_chooseH2Label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

