// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: AqyDisp

#include "../ui.h"

lv_obj_t * ui_ServiceScreen = NULL;
lv_obj_t * ui_readyNumberLabel = NULL;
lv_obj_t * ui_readyNameLabel = NULL;
// event funtions
void ui_event_ServiceScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        checkOrderUpdates(e);
    }
}

// build funtions

void ui_ServiceScreen_screen_init(void)
{
    ui_ServiceScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ServiceScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ServiceScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServiceScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_readyNumberLabel = lv_label_create(ui_ServiceScreen);
    lv_obj_set_width(ui_readyNumberLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_readyNumberLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_readyNumberLabel, 0);
    lv_obj_set_y(ui_readyNumberLabel, -30);
    lv_obj_set_align(ui_readyNumberLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_readyNumberLabel, "#---");
    lv_obj_set_style_text_color(ui_readyNumberLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_readyNumberLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_readyNumberLabel, &ui_font_KazakhFontNovoNumbers140, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_readyNameLabel = lv_label_create(ui_ServiceScreen);
    lv_obj_set_width(ui_readyNameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_readyNameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_readyNameLabel, 0);
    lv_obj_set_y(ui_readyNameLabel, 70);
    lv_obj_set_align(ui_readyNameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_readyNameLabel, "Тапсырысыңызды күтеміз :)");
    lv_obj_set_style_text_color(ui_readyNameLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_readyNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_readyNameLabel, &ui_font_KazakhFontNovo36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ServiceScreen, ui_event_ServiceScreen, LV_EVENT_ALL, NULL);

}

void ui_ServiceScreen_screen_destroy(void)
{
    if(ui_ServiceScreen) lv_obj_del(ui_ServiceScreen);

    // NULL screen variables
    ui_ServiceScreen = NULL;
    ui_readyNumberLabel = NULL;
    ui_readyNameLabel = NULL;

}
