// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_wifiConnectScreen = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_scanWiFiButton = NULL;
lv_obj_t * ui_wifiScanLabel = NULL;
lv_obj_t * ui_wifiPanel = NULL;
lv_obj_t * ui_wifiConnectButton = NULL;
lv_obj_t * ui_wifiConnectLabel = NULL;
lv_obj_t * ui_wifiTextInput = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ota_custom_update(e);
    }
}

// build funtions

void ui_wifiConnectScreen_screen_init(void)
{
    ui_wifiConnectScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_wifiConnectScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiConnectScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiConnectScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_wifiConnectScreen);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 46);
    lv_obj_set_x(ui_Button1, 173);
    lv_obj_set_y(ui_Button1, 119);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Upload");

    ui_scanWiFiButton = lv_button_create(ui_wifiConnectScreen);
    lv_obj_set_width(ui_scanWiFiButton, 100);
    lv_obj_set_height(ui_scanWiFiButton, 50);
    lv_obj_set_x(ui_scanWiFiButton, -168);
    lv_obj_set_y(ui_scanWiFiButton, -114);
    lv_obj_set_align(ui_scanWiFiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scanWiFiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_scanWiFiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiScanLabel = lv_label_create(ui_scanWiFiButton);
    lv_obj_set_width(ui_wifiScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiScanLabel, "Scan");

    ui_wifiPanel = lv_obj_create(ui_wifiConnectScreen);
    lv_obj_set_width(ui_wifiPanel, 298);
    lv_obj_set_height(ui_wifiPanel, 118);
    lv_obj_set_x(ui_wifiPanel, 54);
    lv_obj_set_y(ui_wifiPanel, -82);
    lv_obj_set_align(ui_wifiPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiConnectButton = lv_button_create(ui_wifiConnectScreen);
    lv_obj_set_width(ui_wifiConnectButton, 100);
    lv_obj_set_height(ui_wifiConnectButton, 50);
    lv_obj_set_x(ui_wifiConnectButton, -167);
    lv_obj_set_y(ui_wifiConnectButton, -48);
    lv_obj_set_align(ui_wifiConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_wifiConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiConnectLabel = lv_label_create(ui_wifiConnectButton);
    lv_obj_set_width(ui_wifiConnectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiConnectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiConnectLabel, "Connect");

    ui_wifiTextInput = lv_textarea_create(ui_wifiConnectScreen);
    lv_obj_set_width(ui_wifiTextInput, 84);
    lv_obj_set_height(ui_wifiTextInput, 70);
    lv_obj_set_x(ui_wifiTextInput, 164);
    lv_obj_set_y(ui_wifiTextInput, 32);
    lv_obj_set_align(ui_wifiTextInput, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifiTextInput, "Placeholder...");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_wifiConnectScreen_screen_destroy(void)
{
    if(ui_wifiConnectScreen) lv_obj_del(ui_wifiConnectScreen);

    // NULL screen variables
    ui_wifiConnectScreen = NULL;
    ui_Button1 = NULL;
    ui_Label1 = NULL;
    ui_scanWiFiButton = NULL;
    ui_wifiScanLabel = NULL;
    ui_wifiPanel = NULL;
    ui_wifiConnectButton = NULL;
    ui_wifiConnectLabel = NULL;
    ui_wifiTextInput = NULL;

}
