// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WIFICONNECTSCREEN_H
#define UI_WIFICONNECTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifiConnectScreen
extern void ui_wifiConnectScreen_screen_init(void);
extern void ui_wifiConnectScreen_screen_destroy(void);
extern lv_obj_t * ui_wifiConnectScreen;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_scanWiFiButton;
extern lv_obj_t * ui_wifiScanLabel;
extern lv_obj_t * ui_wifiPanel;
extern lv_obj_t * ui_wifiConnectButton;
extern lv_obj_t * ui_wifiConnectLabel;
extern lv_obj_t * ui_wifiTextInput;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

